<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Loteca IFC</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- colar aqui -->
                <h1>Você selecionou <?= $regrasDoJogo['nome'] ?> </h1>


            </div>
        </div>
    </div>

</body>
</html>