<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Agenda</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

	
	<div class="container" style="margin-top: 30px;">

		<h3>MINHA AGENDA DE CONTATOS</h3>
		<br />
		
		<!-- CADASTRO-->
		<div class="row">
			<div class="col-md-12">
				<form class="form-inline">
				  
				  <!--nome-->
				  <div class="form-group">
				    <label for="nome">Nome</label>
				    <input type="text" class="form-control" id="nome">
				  </div>
				  
				  <!--email-->
				  <div class="form-group">
				    <label for="email">Email</label>
				    <input type="email" class="form-control" id="email">
				  </div>

				  <!--telefone-->
				  <div class="form-group">
				    <label for="telefone">Telefone</label>
				    <input type="text" class="form-control" id="telefone">
				  </div>
				  
				  <button type="submit" class="btn btn-default">CADASTRAR</button>
				
				</form>
			</div>
		</div>

		<br />
		
		<!--CONTATOS-->
		<div class="row">
			<div class="col-md-12">

				<!-- Conteúdo -->
				<table class="table"> 
					<thead> 
						<tr> 
							<th>#</th> 
							<th>Nome</th> 
							<th>Email</th> 
							<th>Telefone</th> 
						</tr> 
					</thead> 
					<tbody> 
						<!-- repetir -->
						<tr> 
							<th scope="row">1</th> 
							<td>John</td> 
							<td>jhon@doe.com</td> 
							<td>(47) 999999999</td> 
						</tr> 
					</tbody> 
				</table>
			</div>
		</div>
	</div>
</body>
</html>